#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
echo "==> Building OpenCoin release binaries..."
cargo build --release
echo ""
echo "==> Binaries:"
echo "  target/release/opencoin-node   (node + pool + RPC)"
echo "  target/release/opencoin-wallet  (wallet CLI)"
echo "  target/release/opencoin-miner   (CPU miner)"
echo ""
echo "==> To install system-wide:"
echo "  sudo cp target/release/opencoin-{node,wallet,miner} /usr/local/bin/"
echo ""
echo "==> Quick start (seed node):"
echo "  opencoin-node start"
echo ""
echo "==> Quick start (mining node):"
echo "  opencoin-node start --seed mail.laat.com.au:9768"
echo ""
echo "==> Quick start (pool node):"
echo "  opencoin-node start --seed mail.laat.com.au:9768 --pool --pool-port 3333"
echo ""
echo "==> Connect miner to pool:"
echo "  opencoin-miner --pool mail.laat.com.au:3333 --address <your-oc-address>"
