#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
echo "==> Building OpenCoin release binaries..."
cargo build --release
echo ""
echo "==> Binaries:"
echo "  target/release/opencoin-node   (node + pool + RPC)"
echo "  target/release/opencoin-wallet  (wallet CLI)"
echo "  target/release/opencoin-miner   (CPU miner)"
echo ""
echo "==> To install system-wide:"
echo "  sudo cp target/release/opencoin-{node,wallet,miner} /usr/local/bin/"
echo ""
echo "==> Quick start (relay node):"
echo "  opencoin-node start"
echo ""
echo "==> Quick start (mining node):"
echo "  opencoin-node start --mine --premine-key YOUR-SECRET-KEY"
echo ""
echo "==> Quick start (pool node):"
echo "  opencoin-node start --pool --pool-port 3333"
echo ""
echo "==> Discover and connect miner to pool:"
echo "  opencoin-miner --discover --address <your-oc-address> --threads 4"
